language: android
jdk: oraclejdk8

# whitelist
branches:
  only:
    - master
    - clean_architecture

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

script:
  ./gradlew build jacoco coveralls
